// ============================================
// BASE DE DONNÉES - DESTINATIONS DISPONIBLES
// ============================================

const countriesData = [
    // LIBYE - AFRIQUE
    {
        id: 1,
        name: "Libye",
        continent: "Afrique",
        emoji: "🇱🇾",
        visaStatus: "no-visa",
        visaText: "Sans visa",
        budget: 300,
        budgetCategory: "low-budget",
        description: "Déserts spectaculaires et patrimoine antique",
        tags: ["culture", "desert"],
        cities: ["Tripoli", "Benghazi", "Derna", "Ghadames"],
        bestPeriod: "Octobre à avril",
        transport: "Vol direct depuis Tunis, voitures de location disponibles",
        security: "Vérifier les avis de voyage, certaines zones peuvent être instables",
        dishes: ["Coucous à la libyenne", "Shorba (soupe épicée)", "Asida", "Mechoui", "Deglet Noor (dattes)"],
        monuments: ["Leptis Magna - ruines romaines", "Sabratha - ancienne ville phénicienne", "Désert de Sahara", "Médina de Tripoli", "Oasis de Ghadames"],
        activities: ["Safari dans le Sahara", "Visite des ruines romaines", "Trek dans le désert", "Exploration des oasis", "Plongée sous-marine"]
    },
    // ALGÉRIE - AFRIQUE
    {
        id: 2,
        name: "Algérie",
        continent: "Afrique",
        emoji: "🇩🇿",
        visaStatus: "with-visa",
        visaText: "Visa requis",
        budget: 400,
        budgetCategory: "low-budget",
        description: "Paysages variés: côtes, déserts et montagnes",
        tags: ["culture", "desert", "beach"],
        cities: ["Alger", "Oran", "Tlemcen", "Tamanrasset"],
        bestPeriod: "Octobre à mai",
        transport: "Ferry depuis Tunis, vols directs, bus disponibles",
        security: "Stable, zones touristiques sûres",
        dishes: ["Chorba frik", "Couscous algérien", "Makroudh", "Merguez", "Tajine d'agneau"],
        monuments: ["Casbah d'Alger", "Tlemcen historique", "Vallée du M'Zab", "Plateau du Tassili", "Ruines de Timgad"],
        activities: ["Visite de la Casbah", "Trek au Tassili N'Ajjer", "Plage à Oran", "Excursion dans le désert", "Visite de musées"]
    },
    // MAROC - AFRIQUE
    {
        id: 3,
        name: "Maroc",
        continent: "Afrique",
        emoji: "🇲🇦",
        visaStatus: "no-visa",
        visaText: "Sans visa (90 jours)",
        budget: 450,
        budgetCategory: "low-budget",
        description: "Médinas colorées, plages et montagnes de l'Atlas",
        tags: ["culture", "beach", "mountain"],
        cities: ["Marrakech", "Fès", "Tanger", "Agadir"],
        bestPeriod: "Octobre à mai",
        transport: "Ferry Tunis-Tanger, vols directs, buses disponibles",
        security: "Très sûr, destination touristique populaire",
        dishes: ["Tagine de poulet aux prunes", "Couscous marocain", "Pastilla", "Harira", "Briouates"],
        monuments: ["Médina de Marrakech", "Médina de Fès", "Kasbahs du Draa", "Montagne Toubkal", "Jemaa el-Fnaa"],
        activities: ["Trekking Atlas", "Visite des souks", "Riad exploration", "Plage à Essaouira", "Excursion au Sahara"]
    },
    // ÉGYPTE - AFRIQUE
    {
        id: 7,
        name: "Égypte",
        continent: "Afrique",
        emoji: "🇪🇬",
        visaStatus: "with-visa",
        visaText: "Visa à l'arrivée",
        budget: 500,
        budgetCategory: "low-budget",
        description: "Pyramides, Nil et merveilles antiques",
        tags: ["culture", "desert"],
        cities: ["Le Caire", "Louxor", "Assouan", "Giza"],
        bestPeriod: "Octobre à avril",
        transport: "Vol direct Tunis-Caire, croisières sur le Nil",
        security: "Stable, zones touristiques sûres",
        dishes: ["Koshari", "Falafel égyptien", "Ful medames", "Ta'ameya", "Konafa"],
        monuments: ["Grandes Pyramides de Giza", "Sphinx", "Vallée des Rois", "Temples de Louxor", "Musée Égyptien"],
        activities: ["Croisière sur le Nil", "Visite des pyramides", "Temple de Louxor", "Vallée des Rois", "Bateau à voile"]
    },
    // JORDANIE - ASIE
    {
        id: 9,
        name: "Jordanie",
        continent: "Asie",
        emoji: "🇯🇴",
        visaStatus: "with-visa",
        visaText: "Visa à l'arrivée",
        budget: 550,
        budgetCategory: "low-budget",
        description: "Pétra, Mer Morte et désert rose",
        tags: ["culture", "desert"],
        cities: ["Amman", "Pétra", "Wadi Rum", "Aqaba"],
        bestPeriod: "Octobre à avril",
        transport: "Vol depuis Tunis, bus, voitures de location",
        security: "Stable et sûr",
        dishes: ["Mensaf jordanien", "Hummus", "Musakhan", "Zarb", "Knafeh"],
        monuments: ["Pétra", "Mer Morte", "Désert rose Wadi Rum", "Château du Désert", "Aqaba plage"],
        activities: ["Randonnée à Pétra", "4x4 Wadi Rum", "Flottaison Mer Morte", "Aqaba plongée", "Châteaux du désert"]
    },
    // TURQUIE - ASIE
    {
        id: 8,
        name: "Turquie",
        continent: "Asie",
        emoji: "🇹🇷",
        visaStatus: "no-visa",
        visaText: "Sans visa (90 jours)",
        budget: 600,
        budgetCategory: "beach",
        description: "Istanbul, côtes turquoises et Cappadoce",
        tags: ["beach", "culture"],
        cities: ["Istanbul", "Antalya", "Cappadoce", "Bodrum"],
        bestPeriod: "Avril à mai, septembre à octobre",
        transport: "Vol depuis Tunis, vols internes",
        security: "Très sûr pour les touristes",
        dishes: ["Kebab turque", "Börek", "Manti", "Baklava", "Ravioli turc"],
        monuments: ["Mosquée Bleue", "Hagia Sophia", "Palais de Topkapi", "Montgolfière en Cappadoce", "Plages de Bodrum"],
        activities: ["Bateau dans le Bosphore", "Montgolfière Cappadoce", "Bazaar d'Istanbul", "Plage en Méditerranée", "Hammam turc"]
    },
    // ESPAÑA (Espagne) - EUROPE
    {
        id: 4,
        name: "Espagne",
        continent: "Europe",
        emoji: "🇪🇸",
        visaStatus: "no-visa",
        visaText: "Sans visa (Schengen)",
        budget: 800,
        budgetCategory: "beach",
        description: "Plages méditerranéennes, architecture et gastronomie",
        tags: ["beach", "culture"],
        cities: ["Barcelone", "Séville", "Madrid", "Málaga"],
        bestPeriod: "Mai à septembre",
        transport: "Vol depuis Tunis (2-3h), locations de voiture",
        security: "Très sûr",
        dishes: ["Paella", "Gazpacho", "Tapas", "Croquetas", "Jamón ibérique"],
        monuments: ["Sagrada Familia", "Alhambra de Grenade", "Alcázar de Séville", "Plage de Barcelone", "Parque Güell"],
        activities: ["Visite de Barcelone", "Plage en Andalousie", "Flamenco à Séville", "Musée du Prado", "Excursion en montagne"]
    },
    // FRANCE - EUROPE
    {
        id: 5,
        name: "France",
        continent: "Europe",
        emoji: "🇫🇷",
        visaStatus: "no-visa",
        visaText: "Sans visa (Schengen)",
        budget: 1000,
        budgetCategory: "culture",
        description: "Capitale parisienne, côte d'azur et provence",
        tags: ["culture", "beach"],
        cities: ["Paris", "Nice", "Lyon", "Marseille"],
        bestPeriod: "Avril à octobre",
        transport: "Vol depuis Tunis, TGV depuis Paris",
        security: "Très sûr",
        dishes: ["Croissants", "Baguette", "Coq au vin", "Bouillabaisse", "Macarons"],
        monuments: ["Tour Eiffel", "Louvre", "Notre-Dame", "Versailles", "Arc de Triomphe"],
        activities: ["Visite du Louvre", "Ballade à Nice", "Musées parisiens", "Provence en voiture", "Côte d'azur"]
    },
    // ITALIE - EUROPE
    {
        id: 6,
        name: "Italie",
        continent: "Europe",
        emoji: "🇮🇹",
        visaStatus: "no-visa",
        visaText: "Sans visa (Schengen)",
        budget: 900,
        budgetCategory: "culture",
        description: "Rome, Venise, côte amalfitaine et Toscane",
        tags: ["culture", "beach"],
        cities: ["Rome", "Venise", "Florence", "Naples"],
        bestPeriod: "Avril à mai, septembre à octobre",
        transport: "Vol depuis Tunis, trains internes",
        security: "Très sûr",
        dishes: ["Pizza napolitaine", "Pâtes carbonara", "Risotto milanais", "Tiramisu", "Panettone"],
        monuments: ["Colosseum (Rome)", "Place Saint-Marc (Venise)", "Duomo (Florence)", "Pompeii", "Fontaine de Trevi"],
        activities: ["Visite du Vatican", "Gondole à Venise", "Galerie Uffizi", "Côte amalfitaine", "Musées romains"]
    },
    // GRÈCE - EUROPE
    {
        id: 10,
        name: "Grèce",
        continent: "Europe",
        emoji: "🇬🇷",
        visaStatus: "no-visa",
        visaText: "Sans visa (Schengen)",
        budget: 750,
        budgetCategory: "beach",
        description: "Îles grecques, Athènes et mer Égée",
        tags: ["beach", "culture"],
        cities: ["Athènes", "Mykonos", "Santorini", "Corfou"],
        bestPeriod: "Mai à septembre",
        transport: "Vol depuis Tunis, ferries inter-îles",
        security: "Très sûr",
        dishes: ["Moussaka", "Souvlaki", "Salade grecque", "Baklava grec", "Ouzo"],
        monuments: ["Parthenon", "Acropole", "Caldera Santorini", "Palais de Knossos", "Temple de Zeus"],
        activities: ["Visite Athènes", "Îles en bateau", "Plage Mykonos", "Coucher soleil Santorini", "Snorkeling"]
    }
];